server.port=8080

spring.datasource.url=${DB_URL:jdbc:sqlite:../maplewood_school.sqlite}
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.use_get_generated_keys=false

logging.level.org.springframework.web=INFO
logging.level.com.maplewood=DEBUG
server.error.include-message=always
server.error.include-stacktrace=on_param
